change: defer to `TF_WORKSPACE` environment variable for `arg-workspace` selection input (#435)
* rely on `TF_WORKSPACE` environment variable input and drop support for `-or-create` argument

Signed-off-by: Rishav Dhar <19497993+rdhar@users.noreply.github.com>

* now to `TF_WORKSPACE` environment variable input instead of `arg-workspace`

Signed-off-by: Rishav Dhar <19497993+rdhar@users.noreply.github.com>

* bump terraform version in test

Signed-off-by: Rishav Dhar <19497993+rdhar@users.noreply.github.com>

* use semver ranges

Signed-off-by: Rishav Dhar <19497993+rdhar@users.noreply.github.com>

* use latest version

Signed-off-by: Rishav Dhar <19497993+rdhar@users.noreply.github.com>

* matrix input array conversion

Signed-off-by: Rishav Dhar <19497993+rdhar@users.noreply.github.com>

* env.TF_WORKSPACE ref

Signed-off-by: Rishav Dhar <19497993+rdhar@users.noreply.github.com>

* remove `-or-create`

Signed-off-by: Rishav Dhar <19497993+rdhar@users.noreply.github.com>

* remove show-args default value of `workspace`

Signed-off-by: Rishav Dhar <19497993+rdhar@users.noreply.github.com>

* some more echo

Signed-off-by: Rishav Dhar <19497993+rdhar@users.noreply.github.com>

* limit scope of test suite

Signed-off-by: Rishav Dhar <19497993+rdhar@users.noreply.github.com>

* echo `command` and `command_append`

Signed-off-by: Rishav Dhar <19497993+rdhar@users.noreply.github.com>

* echo steps.arg.outputs.arg-workspace

Signed-off-by: Rishav Dhar <19497993+rdhar@users.noreply.github.com>

* rearrange

Signed-off-by: Rishav Dhar <19497993+rdhar@users.noreply.github.com>

* clean up echo

Signed-off-by: Rishav Dhar <19497993+rdhar@users.noreply.github.com>

* consolidate `TF_WORKSPACE`

Signed-off-by: Rishav Dhar <19497993+rdhar@users.noreply.github.com>

* oops

Signed-off-by: Rishav Dhar <19497993+rdhar@users.noreply.github.com>

* consistent quotations in comments

Signed-off-by: Rishav Dhar <19497993+rdhar@users.noreply.github.com>

* test empty arg-refresh

Signed-off-by: Rishav Dhar <19497993+rdhar@users.noreply.github.com>

* bump input and output parameter headings

Signed-off-by: Rishav Dhar <19497993+rdhar@users.noreply.github.com>

* docs

Signed-off-by: Rishav Dhar <19497993+rdhar@users.noreply.github.com>

* d

Signed-off-by: Rishav Dhar <19497993+rdhar@users.noreply.github.com>

* d

Signed-off-by: Rishav Dhar <19497993+rdhar@users.noreply.github.com>

* inputs

Signed-off-by: Rishav Dhar <19497993+rdhar@users.noreply.github.com>

* spacing

Signed-off-by: Rishav Dhar <19497993+rdhar@users.noreply.github.com>

* wording

Signed-off-by: Rishav Dhar <19497993+rdhar@users.noreply.github.com>

* order

Signed-off-by: Rishav Dhar <19497993+rdhar@users.noreply.github.com>

* spacing

Signed-off-by: Rishav Dhar <19497993+rdhar@users.noreply.github.com>

* wording

Signed-off-by: Rishav Dhar <19497993+rdhar@users.noreply.github.com>

* wording

Signed-off-by: Rishav Dhar <19497993+rdhar@users.noreply.github.com>

* footer

Signed-off-by: Rishav Dhar <19497993+rdhar@users.noreply.github.com>

* rearrange

Signed-off-by: Rishav Dhar <19497993+rdhar@users.noreply.github.com>

* reminder

Signed-off-by: Rishav Dhar <19497993+rdhar@users.noreply.github.com>

* ready to merge

Signed-off-by: Rishav Dhar <19497993+rdhar@users.noreply.github.com>

---------

Signed-off-by: Rishav Dhar <19497993+rdhar@users.noreply.github.com>

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -19,6 +19,8 @@ runs:
 
     - id: arg
       shell: bash
+      env:
+        TF_WORKSPACE: ${{ env.TF_WORKSPACE || inputs.arg-workspace }}
       run: |
         # Populate variables.
         # Environment variables.
@@ -27,6 +29,7 @@ runs:
         echo TF_CLI_ARGS=$([[ -n "${{ env.TF_CLI_ARGS }}" ]] && echo "${{ env.TF_CLI_ARGS }} -no-color" || echo "-no-color") >> "$GITHUB_ENV"
         echo TF_IN_AUTOMATION="true" >> "$GITHUB_ENV"
         echo TF_INPUT="false" >> "$GITHUB_ENV"
+        echo TF_WORKSPACE="$TF_WORKSPACE" >> "$GITHUB_ENV"
         if [[ "$GITHUB_SERVER_URL" != "https://github.com" ]]; then echo GH_HOST=$(echo "$GITHUB_SERVER_URL" | sed 's/.*:\/\///') >> "$GITHUB_ENV"; fi
 
         # CLI arguments.
@@ -51,7 +54,6 @@ runs:
         echo arg-lockfile=$([[ -n "${{ inputs.arg-lockfile }}" ]] && echo " -lockfile=${{ inputs.arg-lockfile }}" || echo "") >> "$GITHUB_OUTPUT"
         echo arg-migrate-state=$([[ -n "${{ inputs.arg-migrate-state }}" ]] && echo " -migrate-state" || echo "") >> "$GITHUB_OUTPUT"
         echo arg-no-tests=$([[ -n "${{ inputs.arg-no-tests }}" ]] && echo " -no-tests" || echo "") >> "$GITHUB_OUTPUT"
-        echo arg-or-create=$([[ -n "${{ inputs.arg-or-create }}" ]] && echo " -or-create=${{ inputs.arg-or-create }}" || echo "") >> "$GITHUB_OUTPUT"
         echo arg-parallelism=$([[ -n "${{ inputs.arg-parallelism }}" ]] && echo " -parallelism=${{ inputs.arg-parallelism }}" || echo "") >> "$GITHUB_OUTPUT"
         echo arg-plugin-dir=$([[ -n "${{ inputs.arg-plugin-dir }}" ]] && echo " -plugin-dir=${{ inputs.arg-plugin-dir }}" || echo "") >> "$GITHUB_OUTPUT"
         echo arg-reconfigure=$([[ -n "${{ inputs.arg-reconfigure }}" ]] && echo " -reconfigure" || echo "") >> "$GITHUB_OUTPUT"
@@ -67,7 +69,7 @@ runs:
         echo arg-var-file=$([[ -n "${{ inputs.arg-var-file }}" ]] && echo " -var-file=${{ inputs.arg-var-file }}" | sed "s/,/ -var-file=/g" || echo "") >> "$GITHUB_OUTPUT"
         echo arg-var=$([[ -n "${{ inputs.arg-var }}" ]] && echo " -var=${{ inputs.arg-var }}" | sed "s/,/ -var=/g" || echo "") >> "$GITHUB_OUTPUT"
         echo arg-write=$([[ -n "${{ inputs.arg-write }}" ]] && echo " -write=${{ inputs.arg-write }}" || echo "") >> "$GITHUB_OUTPUT"
-        echo arg-workspace=$([[ -n "${{ inputs.arg-workspace }}" ]] && echo " -workspace=${{ inputs.arg-workspace }}" || echo "") >> "$GITHUB_OUTPUT"
+        echo arg-workspace=$([[ -n "$TF_WORKSPACE" ]] && echo " -workspace=$TF_WORKSPACE" || echo "") >> "$GITHUB_OUTPUT"
 
     - id: identifier
       env:
@@ -90,7 +92,7 @@ runs:
         echo "pr=$pr_number" >> "$GITHUB_OUTPUT"
 
         # Generate identifier for the workflow run using MD5 hashing algorithm for concise and unique naming.
-        identifier="${{ steps.arg.outputs.arg-chdir }}${{ inputs.arg-workspace }}${{ steps.arg.outputs.arg-backend-config }}${{ steps.arg.outputs.arg-var-file }}${{ steps.arg.outputs.arg-var }}${{ steps.arg.outputs.arg-replace }}${{ steps.arg.outputs.arg-target }}${{ steps.arg.outputs.arg-destroy }}"
+        identifier="${{ steps.arg.outputs.arg-chdir }}${{ steps.arg.outputs.arg-workspace }}${{ steps.arg.outputs.arg-backend-config }}${{ steps.arg.outputs.arg-var-file }}${{ steps.arg.outputs.arg-var }}${{ steps.arg.outputs.arg-replace }}${{ steps.arg.outputs.arg-target }}${{ steps.arg.outputs.arg-destroy }}"
         identifier=$(echo -n "$identifier" | md5sum | awk '{print $1}')
         echo "name=${{ inputs.tool }}-${pr_number}-${identifier}.tfplan" >> "$GITHUB_OUTPUT"
 
@@ -132,16 +134,6 @@ runs:
         args="${{ steps.arg.outputs.arg-backend-config }}${{ steps.arg.outputs.arg-backend }}${{ inputs.tool == 'tofu' && steps.arg.outputs.arg-var-file || '' }}${{ inputs.tool == 'tofu' && steps.arg.outputs.arg-var || '' }}${{ steps.arg.outputs.arg-force-copy }}${{ steps.arg.outputs.arg-from-module }}${{ steps.arg.outputs.arg-get }}${{ steps.arg.outputs.arg-lock-timeout }}${{ steps.arg.outputs.arg-lock }}${{ steps.arg.outputs.arg-lockfile }}${{ steps.arg.outputs.arg-migrate-state }}${{ steps.arg.outputs.arg-plugin-dir }}${{ steps.arg.outputs.arg-reconfigure }}${{ steps.arg.outputs.arg-test-directory }}${{ steps.arg.outputs.arg-upgrade }}"
         echo "${{ inputs.tool }} init${{ steps.arg.outputs.arg-chdir }}${args}" | sed 's/ -/\n -/g' > tf.command.txt
         ${{ inputs.tool }}${{ steps.arg.outputs.arg-chdir }} init${args} 2> >(tee tf.console.txt) > >(tee tf.console.txt)
-
-    - if: ${{ inputs.arg-workspace != '' && contains(fromJSON('["plan", "apply", "init"]'), inputs.command) }}
-      id: workspace
-      shell: bash
-      run: |
-        # TF workspace select.
-        trap 'exit_code="$?"; echo "exit_code=$exit_code" >> "$GITHUB_OUTPUT"' EXIT
-        args="${{ steps.arg.outputs.arg-or-create }} ${{ inputs.arg-workspace }}"
-        echo "${{ inputs.tool }} workspace select${{ steps.arg.outputs.arg-chdir }}${args}" | sed 's/ -/\n -/g' > tf.command.txt
-        ${{ inputs.tool }}${{ steps.arg.outputs.arg-chdir }} workspace select${args} 2> >(tee tf.console.txt) > >(tee tf.console.txt)
 
     - if: ${{ inputs.validate == 'true' && contains(fromJSON('["plan", "apply", "init"]'), inputs.command) }}
       id: validate
@@ -280,50 +272,51 @@ runs:
       shell: bash
       run: |
         # Post output.
-        # Parse the tf.command.txt file.
+        # Parse the "tf.command.txt" file.
         command=$(cat tf.command.txt)
 
-        # Remove each comma-delemited hide-args argument from the command.
+        # Remove each comma-delemited "hide-args" argument from the command.
         IFS=',' read -ra hide_args <<< "${{ inputs.hide-args }}"
         for arg in "${hide_args[@]}"; do
           command=$(echo "$command" | grep --invert-match "^ -${arg}" || true)
         done
 
-        # Conversely, show each comma-delemited show-args argument in the command.
+        # Conversely, show each comma-delemited "show-args" argument in the command.
         command_append=""
         IFS=',' read -ra show_args <<< "${{ inputs.show-args }}"
         for arg in "${show_args[@]}"; do
-          command_append+=$(echo "${{ steps.arg.outputs.arg-workspace }}${{ steps.arg.outputs.arg-backend-config }}${{ steps.arg.outputs.arg-backend }}${{ steps.arg.outputs.arg-backup }}${{ steps.arg.outputs.arg-check }}${{ steps.arg.outputs.arg-compact-warnings }}${{ steps.arg.outputs.arg-concise }}${{ steps.arg.outputs.arg-destroy }}${{ steps.arg.outputs.arg-detailed-exitcode }}${{ steps.arg.outputs.arg-diff }}${{ steps.arg.outputs.arg-force-copy }}${{ steps.arg.outputs.arg-from-module }}${{ steps.arg.outputs.arg-generate-config-out }}${{ steps.arg.outputs.arg-get }}${{ steps.arg.outputs.arg-list }}${{ steps.arg.outputs.arg-lock-timeout }}${{ steps.arg.outputs.arg-lock }}${{ steps.arg.outputs.arg-lockfile }}${{ steps.arg.outputs.arg-migrate-state }}${{ steps.arg.outputs.arg-no-tests }}${{ steps.arg.outputs.arg-or-create }}${{ steps.arg.outputs.arg-parallelism }}${{ steps.arg.outputs.arg-plugin-dir }}${{ steps.arg.outputs.arg-reconfigure }}${{ steps.arg.outputs.arg-recursive }}${{ steps.arg.outputs.arg-refresh-only }}${{ steps.arg.outputs.arg-refresh }}${{ steps.arg.outputs.arg-replace }}${{ steps.arg.outputs.arg-state-out }}${{ steps.arg.outputs.arg-state }}${{ steps.arg.outputs.arg-target }}${{ steps.arg.outputs.arg-test-directory }}${{ steps.arg.outputs.arg-upgrade }}${{ steps.arg.outputs.arg-var-file }}${{ steps.arg.outputs.arg-var }}${{ steps.arg.outputs.arg-write }}${{ steps.arg.outputs.arg-auto-approve }}" | sed 's/ -/\n -/g' | grep "^ -${arg}" || true)
+          command_append+=$(echo "${{ steps.arg.outputs.arg-workspace }}${{ steps.arg.outputs.arg-backend-config }}${{ steps.arg.outputs.arg-backend }}${{ steps.arg.outputs.arg-backup }}${{ steps.arg.outputs.arg-check }}${{ steps.arg.outputs.arg-compact-warnings }}${{ steps.arg.outputs.arg-concise }}${{ steps.arg.outputs.arg-destroy }}${{ steps.arg.outputs.arg-detailed-exitcode }}${{ steps.arg.outputs.arg-diff }}${{ steps.arg.outputs.arg-force-copy }}${{ steps.arg.outputs.arg-from-module }}${{ steps.arg.outputs.arg-generate-config-out }}${{ steps.arg.outputs.arg-get }}${{ steps.arg.outputs.arg-list }}${{ steps.arg.outputs.arg-lock-timeout }}${{ steps.arg.outputs.arg-lock }}${{ steps.arg.outputs.arg-lockfile }}${{ steps.arg.outputs.arg-migrate-state }}${{ steps.arg.outputs.arg-no-tests }}${{ steps.arg.outputs.arg-parallelism }}${{ steps.arg.outputs.arg-plugin-dir }}${{ steps.arg.outputs.arg-reconfigure }}${{ steps.arg.outputs.arg-recursive }}${{ steps.arg.outputs.arg-refresh-only }}${{ steps.arg.outputs.arg-refresh }}${{ steps.arg.outputs.arg-replace }}${{ steps.arg.outputs.arg-state-out }}${{ steps.arg.outputs.arg-state }}${{ steps.arg.outputs.arg-target }}${{ steps.arg.outputs.arg-test-directory }}${{ steps.arg.outputs.arg-upgrade }}${{ steps.arg.outputs.arg-var-file }}${{ steps.arg.outputs.arg-var }}${{ steps.arg.outputs.arg-write }}${{ steps.arg.outputs.arg-auto-approve }}" | sed 's/ -/\n -/g' | grep "^ -${arg}" || true)
         done
 
+        # Consolidate 'command', taking both "hide-args" and "show-args" into account.
         command=$(echo "$command" | tr -d '\n')$command_append
         echo "command=$command" >> "$GITHUB_OUTPUT"
 
-        # Parse the tf.console.txt file, truncated for character limit.
+        # Parse the "tf.console.txt" file, truncated for character limit.
         console=$(head --bytes=42000 tf.console.txt)
         if [[ ${#console} -eq 42000 ]]; then console="${console}"$'\n…'; fi
         echo "result<<EORESULTTFVIAPR"$'\n'"$console"$'\n'EORESULTTFVIAPR >> "$GITHUB_OUTPUT"
 
-        # Parse the tf.console.txt file for the summary.
+        # Parse the "tf.console.txt" file for the summary.
         summary=$(awk '/^(Error:|Plan:|Apply complete!|No changes.|Success)/ {line=$0} END {if (line) print line; else print "View output."}' tf.console.txt)
         echo "summary=$summary" >> "$GITHUB_OUTPUT"
 
-        # If steps.format.outcome failed, set syntax highlighting to diff, otherwise set it to hcl.
+        # If "steps.format.outcome" failed, set syntax highlighting to "diff", otherwise set it to "hcl".
         syntax="hcl"
         if [[ "${{ steps.format.outcome }}" == "failure" ]]; then syntax="diff"; fi
 
         # Add summary to the job status.
         check_run=$(gh api /repos/${{ github.repository }}/check-runs/${{ steps.identifier.outputs.job }} --header "$GH_API" --method PATCH --field "output[title]=${summary}" --field "output[summary]=${summary}")
 
-        # From check_run, echo html_url.
+        # From "check_run", echo "html_url".
         check_url=$(echo "$check_run" | jq --raw-output '.html_url')
         echo "check_id=$(echo "$check_run" | jq --raw-output '.id')" >> "$GITHUB_OUTPUT"
         run_url=$(echo ${check_url}#step:${{ steps.identifier.outputs.step }}:1)
         echo "run_url=$run_url" >> "$GITHUB_OUTPUT"
 
-        # If tf.diff.txt exists, display it within a diff block, truncated for character limit.
+        # If "tf.diff.txt" exists, display it within a "diff" block, truncated for character limit.
         if [[ -s tf.diff.txt ]]; then
-          # Get count of lines in tf.diff.txt which don't start with "# ".
+          # Get count of lines in "tf.diff.txt" which do not start with "# ".
           diff_count=$(grep --invert-match '^# ' tf.diff.txt | wc --lines)
           if [[ $diff_count -eq 1 ]]; then diff_change="change"; else diff_change="changes"; fi
 
@@ -478,7 +471,7 @@ inputs:
     description: "Check format of TF code (e.g., `false`)."
     required: false
   hide-args:
-    default: "detailed-exitcode,lock,out,var="
+    default: "detailed-exitcode,parallelism,lock,out,var="
     description: "Hide comma-separated arguments from the command input (e.g., `detailed-exitcode,lock,out,var=`)."
     required: false
   label-pr:
@@ -606,10 +599,6 @@ inputs:
   arg-no-tests:
     default: ""
     description: "no-tests"
-    required: false
-  arg-or-create:
-    default: "true"
-    description: "or-create"
     required: false
   arg-parallelism:
     default: ""
