fix: nested matrix structure (#441)
* limit test suite scope

Signed-off-by: Rishav Dhar <19497993+rdhar@users.noreply.github.com>

* fix trigger

Signed-off-by: Rishav Dhar <19497993+rdhar@users.noreply.github.com>

* helpful error message

Signed-off-by: Rishav Dhar <19497993+rdhar@users.noreply.github.com>

* typo

Signed-off-by: Rishav Dhar <19497993+rdhar@users.noreply.github.com>

* retry

Signed-off-by: Rishav Dhar <19497993+rdhar@users.noreply.github.com>

* again

Signed-off-by: Rishav Dhar <19497993+rdhar@users.noreply.github.com>

* huh

Signed-off-by: Rishav Dhar <19497993+rdhar@users.noreply.github.com>

* ready

Signed-off-by: Rishav Dhar <19497993+rdhar@users.noreply.github.com>

* tidy up error message

Signed-off-by: Rishav Dhar <19497993+rdhar@users.noreply.github.com>

* nested matrix

Signed-off-by: Rishav Dhar <19497993+rdhar@users.noreply.github.com>

* flatten nested matrix

Signed-off-by: Rishav Dhar <19497993+rdhar@users.noreply.github.com>

* revert test suite

Signed-off-by: Rishav Dhar <19497993+rdhar@users.noreply.github.com>

---------

Signed-off-by: Rishav Dhar <19497993+rdhar@users.noreply.github.com>

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -106,7 +106,7 @@ runs:
           job_id=$(echo "$workflow_run" | jq --raw-output '(.jobs[] | select((.name | ascii_downcase | gsub("-|_"; " ")) == (env.GITHUB_JOB | ascii_downcase | gsub("-|_"; " "))) | .id) // .jobs[0].id' | tail -n 1)
         else
           # For matrix jobs, join the matrix values with comma separator into a single string and get the ID of the job which contains it.
-          matrix=$(echo "$GH_MATRIX" | jq --raw-output 'to_entries | map(.value) | join(", ")')
+          matrix=$(echo "$GH_MATRIX" | jq --raw-output 'to_entries | map(if .value | type == "object" then (.value | to_entries[0].value) else .value end) | join(", ")')
           job_id=$(echo "$workflow_run" | jq --raw-output --arg matrix "$matrix" '.jobs[] | select(.name | contains($matrix)) | .id' | tail -n 1)
         fi
         echo "job=$job_id" >> "$GITHUB_OUTPUT"
@@ -168,7 +168,8 @@ runs:
       run: |
         # Download plan file.
         # Get the artifact ID of the latest matching plan files for download.
-        artifact_id=$(gh api /repos/${{ github.repository }}/actions/artifacts --header "$GH_API" --method GET --field "name=${{ steps.identifier.outputs.name }}" --jq '.artifacts[0].id')
+        artifact_id=$(gh api /repos/${{ github.repository }}/actions/artifacts --header "$GH_API" --method GET --field "name=${{ steps.identifier.outputs.name }}" --jq '.artifacts[0].id' 2>/dev/null)
+        if [ -z "$artifact_id" ]; then echo "Unable to locate plan file: ${{ steps.identifier.outputs.name }}." && exit 1; fi
         gh api /repos/${{ github.repository }}/actions/artifacts/${artifact_id}/zip --header "$GH_API" --method GET > "${{ steps.identifier.outputs.name }}.zip"
 
         # Unzip the plan file to the working directory, then clean up the zip file.
